# Generated by Django 5.2.6 on 2025-10-01 23:00

import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_auto_20251001_2157"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="marketing_emails",
            new_name="email_notifications",
        ),
        migrations.AddField(
            model_name="customuser",
            name="account_locked_until",
            field=models.DateTimeField(
                blank=True, help_text="Account locked until this time", null=True
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="consent_date",
            field=models.DateTimeField(
                blank=True, help_text="When user gave consent", null=True
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="data_processing_consent",
            field=models.BooleanField(
                default=False, help_text="GDPR data processing consent"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="failed_login_attempts",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of consecutive failed login attempts"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_phone_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="last_login_ip",
            field=models.GenericIPAddressField(
                blank=True, help_text="IP address of last login", null=True
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="last_password_change",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="When user last changed password",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="marketing_emails",
            field=models.BooleanField(
                default=False, help_text="Consent to receive marketing emails"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="password_reset_required",
            field=models.BooleanField(
                default=False, help_text="Force password reset on next login"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="two_factor_enabled",
            field=models.BooleanField(
                default=False, help_text="Whether user has enabled 2FA"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="login_notifications",
            field=models.BooleanField(
                default=True, help_text="Email notifications for new logins"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="push_notifications",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="security_alerts",
            field=models.BooleanField(
                default=True, help_text="Email alerts for security events"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                help_text="Phone number for SMS notifications and 2FA",
                max_length=128,
                null=True,
                region=None,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="Profile picture (max 2MB)",
                null=True,
                upload_to="avatars/%Y/%m/%d/",
            ),
        ),
        migrations.CreateModel(
            name="EmailVerificationToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=128, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("is_used", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_verification_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Verification Token",
                "verbose_name_plural": "Email Verification Tokens",
            },
        ),
        migrations.CreateModel(
            name="LoginAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField(blank=True)),
                (
                    "attempt_type",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("blocked", "Blocked"),
                        ],
                        max_length=10,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("failure_reason", models.CharField(blank=True, max_length=100)),
                ("two_factor_used", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="login_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Login Attempt",
                "verbose_name_plural": "Login Attempts",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="SecurityEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("password_change", "Password Change"),
                            ("password_reset", "Password Reset"),
                            ("2fa_enabled", "2FA Enabled"),
                            ("2fa_disabled", "2FA Disabled"),
                            ("account_locked", "Account Locked"),
                            ("account_unlocked", "Account Unlocked"),
                            ("email_verified", "Email Verified"),
                            ("profile_updated", "Profile Updated"),
                            ("suspicious_activity", "Suspicious Activity"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="security_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Security Event",
                "verbose_name_plural": "Security Events",
                "ordering": ["-timestamp"],
            },
        ),
    ]
