#!/usr/bin/env python3
"""
Security Setup Script for E-commerce Platform

This script implements critical security fixes and generates secure configurations.
Run this script before deploying to production.

Usage:
    python scripts/security_setup.py [--environment production]
"""

import os
import secrets
import string
import subprocess
import sys
from pathlib import Path
from typing import Dict, List


def generate_secret_key() -> str:
    """Generate a secure Django secret key."""
    chars = string.ascii_letters + string.digits + '!@#$%^&*()_+-=[]{}|;:,.<>?'
    return ''.join(secrets.choice(chars) for _ in range(50))


def generate_jwt_secret() -> str:
    """Generate a secure JWT secret key."""
    return secrets.token_urlsafe(64)


def create_env_file(environment: str = 'development') -> None:
    """Create a secure .env file with generated secrets."""
    
    backend_dir = Path(__file__).parent.parent / 'backend'
    env_file = backend_dir / '.env'
    
    # Generate secure keys
    secret_key = generate_secret_key()
    jwt_secret = generate_jwt_secret()
    
    # Environment-specific settings
    if environment == 'production':
        debug = 'False'
        allowed_hosts = 'yourdomain.com,www.yourdomain.com'
        csrf_secure = 'True'
        session_secure = 'True'
        ssl_redirect = 'True'
        cors_allow_all = 'False'
        cors_origins = 'https://yourdomain.com,https://www.yourdomain.com'
        database_url = 'postgresql://username:password@hostname:port/database_name'
    else:
        debug = 'True'
        allowed_hosts = 'localhost,127.0.0.1'
        csrf_secure = 'False'
        session_secure = 'False'
        ssl_redirect = 'False'
        cors_allow_all = 'True'
        cors_origins = 'http://localhost:3000,http://127.0.0.1:3000'
        database_url = 'sqlite:///db.sqlite3'
    
    env_content = f"""# Auto-generated secure environment configuration
# Generated by security_setup.py for {environment} environment
# Generated at: {subprocess.check_output(['date'], text=True).strip()}

# =================================================================
# CRITICAL SECURITY SETTINGS
# =================================================================

SECRET_KEY={secret_key}
DEBUG={debug}
ALLOWED_HOSTS={allowed_hosts}

# =================================================================
# DATABASE & CACHE
# =================================================================

DATABASE_URL={database_url}
REDIS_URL=redis://localhost:6379/0

# =================================================================
# SECURITY SETTINGS
# =================================================================

# HTTPS
SECURE_SSL_REDIRECT={ssl_redirect}
SECURE_PROXY_SSL_HEADER=HTTP_X_FORWARDED_PROTO,https

# Cookies
CSRF_COOKIE_SECURE={csrf_secure}
SESSION_COOKIE_SECURE={session_secure}
CSRF_COOKIE_HTTPONLY=True
SESSION_COOKIE_HTTPONLY=True

# CORS
CORS_ALLOW_ALL_ORIGINS={cors_allow_all}
CORS_ALLOWED_ORIGINS={cors_origins}

# JWT (if using)
JWT_SECRET_KEY={jwt_secret}
JWT_ACCESS_TOKEN_LIFETIME=15
JWT_REFRESH_TOKEN_LIFETIME=1440

# =================================================================
# API CONFIGURATION
# =================================================================

API_RATE_LIMIT_PER_MINUTE=100
API_RATE_LIMIT_AUTHENTICATED=1000

# =================================================================
# EMAIL CONFIGURATION (UPDATE WITH YOUR SETTINGS)
# =================================================================

EMAIL_BACKEND=django.core.mail.backends.console.EmailBackend
# EMAIL_HOST=smtp.gmail.com
# EMAIL_PORT=587
# EMAIL_USE_TLS=True
# EMAIL_HOST_USER=your-email@gmail.com
# EMAIL_HOST_PASSWORD=your-app-password

# =================================================================
# MONITORING
# =================================================================

LOG_LEVEL=INFO
ENVIRONMENT={environment}
"""
    
    # Write the file
    with open(env_file, 'w') as f:
        f.write(env_content)
    
    print(f"✅ Created secure .env file: {env_file}")
    print(f"🔒 Generated SECRET_KEY: {secret_key[:20]}...")
    print(f"🔐 Generated JWT_SECRET: {jwt_secret[:20]}...")


def update_django_settings(environment: str = 'development') -> None:
    """Update Django settings to include security configurations."""
    
    backend_dir = Path(__file__).parent.parent / 'backend'
    settings_dir = backend_dir / 'config' / 'settings'
    
    # Update base.py to import security settings
    base_py = settings_dir / 'base.py'
    
    # Add security imports to base.py
    security_import = """
# Import security settings
try:
    from .security import *
    MIDDLEWARE = ['apps.core.middleware.SecurityHeadersMiddleware'] + MIDDLEWARE
    MIDDLEWARE.append('apps.core.middleware.RequestLoggingMiddleware')
    MIDDLEWARE.append('apps.core.middleware.IPBlockingMiddleware')
    MIDDLEWARE.append('apps.core.middleware.APIRateLimitMiddleware')
except ImportError:
    pass
"""
    
    # Read current base.py content
    if base_py.exists():
        with open(base_py, 'r') as f:
            content = f.read()
        
        # Add security imports if not already present
        if 'from .security import *' not in content:
            with open(base_py, 'a') as f:
                f.write(security_import)
            print(f"✅ Updated Django settings: {base_py}")
    
    # Update production.py for production environment
    if environment == 'production':
        prod_py = settings_dir / 'production.py'
        
        production_security = '''"""Production settings with enhanced security."""
from .base import *
import os

# Security Settings
DEBUG = False
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '').split(',')

# HTTPS Settings
SECURE_SSL_REDIRECT = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_HSTS_SECONDS = 31536000
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

# Cookie Security
CSRF_COOKIE_SECURE = True
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Strict'
SESSION_COOKIE_SECURE = True
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Strict'

# CORS Security
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOWED_ORIGINS = os.getenv('CORS_ALLOWED_ORIGINS', '').split(',')

# Database from environment
import dj_database_url
DATABASES['default'] = dj_database_url.config(
    default=os.getenv('DATABASE_URL')
)

# Cache Configuration
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': os.getenv('REDIS_URL', 'redis://localhost:6379/0'),
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    }
}

# Email Configuration
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() == 'true'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')

# Logging for Production
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': '/var/log/django/ecommerce.log',
            'maxBytes': 1024*1024*15,  # 15MB
            'backupCount': 10,
            'formatter': 'verbose',
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['file', 'console'],
        'level': 'INFO',
    },
}
'''
        
        with open(prod_py, 'w') as f:
            f.write(production_security)
        print(f"✅ Created production settings: {prod_py}")


def install_security_packages() -> None:
    """Install required security packages."""
    
    backend_dir = Path(__file__).parent.parent / 'backend'
    
    security_packages = [
        'django-ratelimit>=4.1.0',
        'bleach>=6.1.0',
        'django-cors-headers>=4.3.0',
        'python-decouple>=3.8',
        'dj-database-url>=3.0.1',
        'django-redis>=5.4.0',
        'gunicorn>=21.2.0',  # Production WSGI server
    ]
    
    # Update pyproject.toml
    pyproject_toml = backend_dir / 'pyproject.toml'
    
    if pyproject_toml.exists():
        with open(pyproject_toml, 'r') as f:
            content = f.read()
        
        # Add security packages if not present
        for package in security_packages:
            package_name = package.split('>=')[0].split('==')[0]
            if package_name not in content:
                # Add to dependencies
                dependencies_section = content.find('dependencies = [')
                if dependencies_section != -1:
                    end_bracket = content.find(']', dependencies_section)
                    if end_bracket != -1:
                        content = (content[:end_bracket] + 
                                 f'    "{package}",\n' + 
                                 content[end_bracket:])
        
        with open(pyproject_toml, 'w') as f:
            f.write(content)
        
        print(f"✅ Updated dependencies in: {pyproject_toml}")


def create_security_tests() -> None:
    """Create basic security tests."""
    
    backend_dir = Path(__file__).parent.parent / 'backend'
    test_file = backend_dir / 'apps' / 'core' / 'test_security.py'
    
    test_content = '''"""
Security tests for the e-commerce platform.
"""
import pytest
from django.test import TestCase, Client, override_settings
from django.urls import reverse
from django.contrib.auth import get_user_model
from django.conf import settings


User = get_user_model()


class SecurityHeadersTestCase(TestCase):
    """Test security headers are present."""
    
    def setUp(self):
        self.client = Client()
    
    def test_security_headers_present(self):
        """Test that security headers are present in responses."""
        response = self.client.get('/')
        
        # Check for security headers
        expected_headers = [
            'X-Content-Type-Options',
            'X-Frame-Options', 
            'X-XSS-Protection',
        ]
        
        for header in expected_headers:
            self.assertIn(header, response)
    
    def test_x_frame_options_deny(self):
        """Test X-Frame-Options is set to DENY."""
        response = self.client.get('/')
        self.assertEqual(response['X-Frame-Options'], 'DENY')
    
    def test_content_type_options_nosniff(self):
        """Test X-Content-Type-Options is set to nosniff."""
        response = self.client.get('/')
        self.assertEqual(response['X-Content-Type-Options'], 'nosniff')


class AuthenticationSecurityTestCase(TestCase):
    """Test authentication security measures."""
    
    def setUp(self):
        self.client = Client()
        self.user = User.objects.create_user(
            email='test@example.com',
            username='testuser',
            password='SecurePass123!'
        )
    
    def test_login_rate_limiting(self):
        """Test that login attempts are rate limited."""
        login_url = reverse('admin:login')  # Using admin login for test
        
        # Make multiple failed login attempts
        for i in range(6):
            response = self.client.post(login_url, {
                'username': 'wrong@example.com',
                'password': 'wrongpassword'
            })
        
        # The 6th attempt should be rate limited
        # Note: This test depends on rate limiting middleware being active
        # In a real implementation, you'd check for 429 status or similar
    
    def test_password_validation(self):
        """Test password validation requirements."""
        # Attempt to create user with weak password
        with self.assertRaises(Exception):  # Should raise validation error
            User.objects.create_user(
                email='weak@example.com',
                username='weakuser',
                password='123'  # Too weak
            )


class CSRFProtectionTestCase(TestCase):
    """Test CSRF protection is active."""
    
    def setUp(self):
        self.client = Client(enforce_csrf_checks=True)
    
    def test_csrf_protection_active(self):
        """Test that CSRF protection is enforced."""
        # This would typically test a form submission without CSRF token
        # and expect a 403 Forbidden response
        pass


class InputValidationTestCase(TestCase):
    """Test input validation and sanitization."""
    
    def test_xss_prevention(self):
        """Test that XSS attempts are prevented."""
        # Test cases for XSS prevention would go here
        malicious_inputs = [
            '<script>alert("xss")</script>',
            'javascript:alert("xss")',
            '<img src="x" onerror="alert(\\'xss\\')">',
        ]
        
        for malicious_input in malicious_inputs:
            # Test that malicious input is properly escaped/sanitized
            # Implementation depends on your specific forms and views
            pass
    
    def test_sql_injection_prevention(self):
        """Test that SQL injection is prevented."""
        # Test cases for SQL injection prevention
        malicious_inputs = [
            "'; DROP TABLE users; --",
            "1' OR '1'='1",
            "admin'/*",
        ]
        
        for malicious_input in malicious_inputs:
            # Test that malicious SQL is not executed
            # Django ORM should prevent this automatically
            pass


@override_settings(DEBUG=False)
class ProductionSecurityTestCase(TestCase):
    """Test production security configuration."""
    
    def test_debug_disabled(self):
        """Test that DEBUG is False in production."""
        self.assertFalse(settings.DEBUG)
    
    def test_secret_key_not_default(self):
        """Test that SECRET_KEY is not the default insecure key."""
        self.assertNotIn('django-insecure', settings.SECRET_KEY)
    
    def test_allowed_hosts_configured(self):
        """Test that ALLOWED_HOSTS is properly configured."""
        # Should not contain wildcard in production
        if not settings.DEBUG:
            self.assertNotIn('*', settings.ALLOWED_HOSTS)
'''
    
    # Create the test file
    test_file.parent.mkdir(parents=True, exist_ok=True)
    with open(test_file, 'w') as f:
        f.write(test_content)
    
    print(f"✅ Created security tests: {test_file}")


def run_security_checks() -> List[str]:
    """Run Django security checks and return any issues."""
    
    backend_dir = Path(__file__).parent.parent / 'backend'
    
    try:
        # Change to backend directory
        os.chdir(backend_dir)
        
        # Run Django security check
        result = subprocess.run(
            ['python', 'manage.py', 'check', '--deploy'],
            capture_output=True,
            text=True
        )
        
        issues = []
        if result.returncode != 0:
            issues.extend(result.stdout.split('\n'))
            issues.extend(result.stderr.split('\n'))
        
        return [issue for issue in issues if issue.strip()]
    
    except Exception as e:
        return [f"Error running security check: {e}"]


def main():
    """Main security setup function."""
    
    # Parse command line arguments
    environment = 'development'
    if len(sys.argv) > 1:
        if '--environment' in sys.argv:
            env_index = sys.argv.index('--environment')
            if env_index + 1 < len(sys.argv):
                environment = sys.argv[env_index + 1]
    
    print("🔒 E-commerce Platform Security Setup")
    print("=" * 50)
    print(f"Environment: {environment}")
    print()
    
    # Step 1: Create secure environment file
    print("Step 1: Creating secure environment configuration...")
    create_env_file(environment)
    print()
    
    # Step 2: Update Django settings
    print("Step 2: Updating Django settings...")
    update_django_settings(environment)
    print()
    
    # Step 3: Install security packages
    print("Step 3: Updating security dependencies...")
    install_security_packages()
    print()
    
    # Step 4: Create security tests
    print("Step 4: Creating security tests...")
    create_security_tests()
    print()
    
    # Step 5: Run security checks
    print("Step 5: Running Django security checks...")
    issues = run_security_checks()
    
    if issues:
        print("⚠️  Security issues found:")
        for issue in issues:
            if issue.strip():
                print(f"   - {issue}")
    else:
        print("✅ No security issues found!")
    print()
    
    # Final summary
    print("🎉 Security Setup Complete!")
    print("=" * 50)
    print("Next steps:")
    print("1. Review the generated .env file and update with your values")
    print("2. Install dependencies: cd backend && uv sync")
    print("3. Run migrations: python manage.py migrate")
    print("4. Run security tests: python manage.py test apps.core.test_security")
    print("5. Deploy with HTTPS and review production checklist")
    print()
    
    if environment == 'production':
        print("⚠️  PRODUCTION DEPLOYMENT REMINDER:")
        print("- Ensure HTTPS is configured")
        print("- Update database credentials")
        print("- Configure email settings")
        print("- Set up monitoring and backups")
        print("- Complete the production security checklist")


if __name__ == '__main__':
    main()